name: HTMACat-test

on:
  push:
    branches: [ dev,master ]
  pull_request:
    branches: [ dev,master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ase numpy==1.21.5 scikit-learn
        pip install https://raw.githubusercontent.com/stanfordbshan/HTMACat-kit/master/requires_wheel/FireWorks-2.0.3-py3-none-any.whl
        pip install https://raw.githubusercontent.com/stanfordbshan/HTMACat-kit/master/requires_wheel/CatKit-0.5.4-py3-none-any.whl
        pip install wheel
        pip install pytest
        sudo -E apt-get install zip 
        # pip install -r requirements.txt
    - name: Install whl file
      run: |
        cd ./src
        python setup.py bdist_wheel
        pip install dist/*.whl
    - name: unzip
      run: |
        cd ./tests
        unzip results.zip -d .

    - name: Run adsorption tests
      run: |
        pytest tests/test_ads.py
    
    - name: Run coadsorption tests
      run: |
        pytest tests/test_coads.py


        
